### ISSUE TITLE
Symlink to . makes find_duplicate_files blow up

### ISSUE THREAD

**Issue by RebelPhoton** [hp310780/FindDuplicateFiles#2]
Final Cut Pro X project files are saved in .fcpbundle files which are actually directories. Inside them there's a .fcpcache that symlinks to .
```Makey_test_conform.fcpbundle# ls -al
total 131
drwxr-xr-x  8 daniel staff     15 Oct 19 21:47  .
drwxr-xr-x 47 daniel staff     53 Nov 11 13:20  ..
drwxr-xr-x  2 daniel staff      3 Oct 17 21:38  17-10-2019
drwxr-xr-x  9 daniel staff     10 Oct 19 21:47  3.1_BOBINAS
drwxr-xr-x  4 daniel staff      5 Oct 18 17:43 '3.1_BOBINAS 2'
-rw-r--r--  1 daniel staff 131072 Oct 17 21:39  CurrentVersion.flexolibrary
-rw-r--r--  1 daniel staff    324 Oct 17 21:12  CurrentVersion.plist
lrwxrwxrwx  1 daniel staff      1 Oct 18 19:11  .fcpcache -> .
-rw-rw-rw-  1 daniel staff      0 Oct 17 21:12  .lock
drwxr-xr-x  2 daniel staff      2 Oct 18 19:11  .lock-dir
-rw-r--r--  1 daniel staff    369 Oct 18 19:11  .lock-info
drwxr-xr-x  2 daniel staff      2 Oct 17 21:12 'Motion Templates.localized'
-rw-r--r--  1 daniel staff    331 Oct 17 21:39  Settings.plist
-rw-r--r--  1 daniel staff      0 Oct 19 21:47  __Sync__
drwxr-xr-x  2 daniel staff      2 Oct 17 21:12  __Temp
```
This makes the recursive dir walker blow up ad infinitum

`WARNING:root:Could not stat: /jupiter/ingest/Areca/MAKEY/03_PROYECTOS_FINAL/Makey_test_conform.fcpbundle/.fcpcache/.fcpcache/.fcpcache/3.1_BOBINAS/Original Media/Traffic City 02.caf. Skipping. [Errno 2] No such file or directory: '/jupiter/ingest/Areca/MAKEY/03_PROYECTOS_FINAL/Makey_test_conform.fcpbundle/.fcpcache/.fcpcache/.fcpcache/3.1_BOBINAS/Original Media/Traffic City 02.caf'
WARNING:root:Could not stat: /jupiter/ingest/Areca/MAKEY/03_PROYECTOS_FINAL/Makey_test_conform.fcpbundle/.fcpcache/.fcpcache/.fcpcache/3.1_BOBINAS/Original Media/z004014.wav. Skipping. [Errno 2] No such file or directory: 
`
[...]
`WARNING:root:Could not stat: /jupiter/ingest/Areca/MAKEY/03_PROYECTOS_FINAL/Makey_test_conform.fcpbundle/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/3.1_BOBINAS/Original Media/Z032008.wav. Skipping. [Errno 2] No such file or directory: '/jupiter/ingest/Areca/MAKEY/03_PROYECTOS_FINAL/Makey_test_conform.fcpbundle/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/3.1_BOBINAS/Original Media/Z032008.wav'
WARNING:root:Could not stat: /jupiter/ingest/Areca/MAKEY/03_PROYECTOS_FINAL/Makey_test_conform.fcpbundle/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/3.1_BOBINAS/Original Media/B085C004_190531_R3IM.mov. Skipping. [Errno 2] No such file or directory: '/jupiter/ingest/Areca/MAKEY/03_PROYECTOS_FINAL/Makey_test_conform.fcpbundle/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/3.1_BOBINAS/Original Media/B085C004_190531_R3IM.mov'`

Cant this be prevented in the code, or can I tell it to ignore those files somehow?

Thanks.

**Comment by hp310780** [comment]
Hi @RebelPhoton , thank you for logging this issue. Cyclical symlinks should be fixed in the latest release (2.1.0) - https://pypi.org/project/find-duplicate-files/#history.

Thanks!
